### ISSUE TITLE
PCM not commutative?

### ISSUE THREAD

**Issue by stklik** [cjekel/similarity_measures#34]
I just noticed that pcm produces different outcomes, depending on which curve is provided first.  
This seems somewhat confusing. Is this intended behaviour?

Here's some example code to reproduce:

```python
import numpy as np
import similaritymeasures

# Generate random experimental data
x = np.random.random(100)
y = np.random.random(100)
exp_data = np.zeros((100, 2))
exp_data[:, 0] = x
exp_data[:, 1] = y

# Generate random numerical data
x = np.random.random(100)
y = np.random.random(100)
num_data = np.zeros((100, 2))
num_data[:, 0] = x
num_data[:, 1] = y

# quantify the difference between the two curves using PCM
pcm = similaritymeasures.pcm(exp_data, num_data)
pcm2 = similaritymeasures.pcm(num_data, exp_data)
print(pcm, pcm2)  # Different! e.g. 23.981105082585927 24.453786363316954

# quantify the difference between the two curves using
# Discrete Frechet distance
df = similaritymeasures.frechet_dist(exp_data, num_data)
df2 = similaritymeasures.frechet_dist(num_data, exp_data)
print(df, df2)  # Same! 1.063735865443663 1.063735865443663

```

**Comment by cjekel** [comment]
It's because of the normalization scheme. I think I have implemented it correctly as described in their paper, but essentially one curve is always normalized to the other one. This is fine if one curve never changes, but would create issues when both curves are changing.

See point 1, page 4 of https://www.dynalook.com/conferences/8th-european-ls-dyna-conference/session-4/Session4_Paper2.pdf 

I do not have a note in the docstring documenting this. Right now the data is always normalized to exp_data.

Feel free to send a PR that would make this better documented!

**Comment by stklik** [comment]
Thanks for the quick reply.  Looking at the code and the paper, indeed, I understand the reasoning. 
However, this makes it difficult to use for our specific purpose.
I now went ahead and wrote myself a little wrapper that calculates as follows:

```
def commutative_pcm(exp_data, num_data):
    pcm1 = similaritymeasures.pcm(exp_data, num_data)
    pcm2 = similaritymeasures.pcm(num_data, exp_data)
    return (pcm1 + pcm2) / 2
```

I'll go ahead and close this issue.
